
# Site settings
title: Haikuo Li
name: Haikuo Li
subtitle: Bioscience Ph.D. Student
email: haikuo.li@wustl.edu
description: >
Bioscience Ph.D. Student
baseurl: ""
url: "https://haikuoli.github.io/"
github_username:  HaikuoLi
disqus_baseurl: "https://haikuoli.github.io/"
disqus_shortname: https-haikuoli-github-io
permalink: :title

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Haikuo Li"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: Twitter
    icon: twitter
    username: HaikuoLi
    url: https://twitter.com/HaikuoLi
    desc: Connect with me on Twitter
    share: true

  - name: LinkedIn
    icon: linkedin
    username: Haikuo Li
    url: https://www.linkedin.com/in/haikuoli/
    desc: Connect with me on LinkedIn
    share: true
